### ISSUE TITLE
create a new, easier to manage website

### ISSUE THREAD

**Issue by val-pf** [resbazaz/website#62]
Apparently there is a 2018 attempt here: https://github.com/resbazaz/resbazaz.github.io

**Comment by val-pf** [comment]
I cannot assign, but assignees are @alex-r-bigelow @hidyverse @julianpistorius and @jcoliver according to my memory.

**Comment by alex-r-bigelow** [comment]
My (very WIP) attempt to build a fresh thing from scratch this morning: https://github.com/alex-r-bigelow/resbazaz-11ty-experiment/

Live site: https://sweet-crepe-acdce8.netlify.app/

It uses:

- 11ty (simpler Javascript-based alternative to Jekyll that still uses markdown and HTML includes in a similar way... so it might not be *too* painful to migrate all our existing stuff)
- Includes a Netlify CMS, so that steering committee members could (in theory; still not sure about this in practice) edit stuff via an `/admin` page right on the site, without messing with the command line
  - The limits of their free tier *might* be enough for something as simple as our site, but if not, we can always drop the CMS support and just keep 11ty for free

**Comment by hidyverse** [comment]
@alex-r-bigelow thanks for this mock-up! Your skills are incomparable!! 

My biggest concern for this migration is allowing for contributions from everyone in the resbazaz community. 

Does this workflow allow for us to clone the repo, make local changes, render a mock-up locally, and then push the changes to a pull request?

**Comment by alex-r-bigelow** [comment]
Yes, the clone + change + render locally + commit + PR path is definitely still doable (and might be a tiny bit easier with only an `npm install` instead of the ruby setup requirement that Jekyll had). I haven't updated the README yet, but this *should* work:

```
# may need to tweak these first lines if you don't have curl and/or are using something other than zsh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.zshrc

nvm install node

git clone https://github.com/alex-r-bigelow/resbazaz-11ty-experiment.git
cd resbazaz-11ty-experiment

npm install
npm build
npm serve
```

Most of the CMS experiment is just to see if we can enable an additional, easier path to edit directly from the site itself. But you're correct that it might be challenging to make that route inclusive. I *think* there's a way to configure the CMS to authenticate just with github credentials (without needing a netlify account) and make edits as long as you have permissions on the repository... but that might not actually be the case (the stuff I was reading implied that you could, but it was a little vague). And even if it is possible, it might not be a feature available on the free tier

**Comment by julianpistorius** [comment]
AFAIK this is the current URL: https://alex-r-bigelow.github.io/resbazaz-11ty-experiment/

**Comment by alex-r-bigelow** [comment]
Yes! I made a little progress over the weekend (still have LOTS to do) but that particular location does some weird things with things like image paths, so running via `localhost` will give you the most accurate preview

**Comment by julianpistorius** [comment]
Thanks @alex-r-bigelow! :bow:

**Comment by Aariq** [comment]
Perhaps Quarto? https://quarto.org/docs/websites/

I think this meets the following needs well:

- Easy to edit content even if all you know is markdown (and a little bit of YAML).
- Customizable theme with SCSS/CSS ontop of Bootswatch
- Can do programmatic stuff like data visualizations, interfacing with GitHub API to get contributors, etc. because it can execute and render code output from Python, R, Julia, ObservableJS, etc.
- Easy deployment to GitHub pages or Netlify
- Can render formats that many of us are familiar with to HTML such as .md, .Rmd, .Qmd, and .ipynb

A gallery of Quarto websites to get an idea of what they can look like/do: https://quarto.org/docs/gallery/#websites
